import './global.css';
import { headers } from 'next/headers';
import { getServerSession } from 'next-auth';
import { authOptions } from '../../../ustad-web-yesildefter/src/app/api/auth/auth.config';
import { AuthProvider } from '@shared/auth/AuthContext';
export const metadata = {
  title: 'Welcome to ustad-web-shell',
  description: 'Generated by create-nx-workspace',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);
  const headersList = headers();

  return (
    <html lang="en">
      <body>
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
